/*
 * Copyright (C) 2015 AppTik Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ../wire-runtime/src/test/proto/person.proto
package io.apptik.comm.jus.converter;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.STRING;
import static com.squareup.wire.Message.Label.OPTIONAL;

public final class Phone extends Message {

  public static final String DEFAULT_PHONE = "";

  @ProtoField(tag = 1, type = STRING, label = OPTIONAL)
  public final String number;

  public Phone(String number) {
    this.number = number;
  }

  private Phone(Builder builder) {
    this(builder.number);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof Phone)) return false;
    Phone o = (Phone) other;
    return equals(number, o.number);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = number != null ? number.hashCode() : 0;
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<Phone> {

    public String number;

    public Builder() {
    }

    public Builder(Phone message) {
      super(message);
      if (message == null) return;
      this.number = message.number;
    }

    public Builder number(String name) {
      this.number = name;
      return this;
    }

    @Override
    public Phone build() {
      checkRequiredFields();
      return new Phone(this);
    }
  }
}
