/*
 * Copyright (C) 2015 AppTik Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: test.proto at 2:1
package io.apptik.comm.jus.converter;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.internal.Internal;

import java.io.IOException;

import okio.ByteString;

public final class Phone extends Message<Phone, Phone.Builder> {
  public static final ProtoAdapter<Phone> ADAPTER = new ProtoAdapter<Phone>(FieldEncoding.LENGTH_DELIMITED, Phone.class) {
    @Override
    public int encodedSize(Phone value) {
      return (value.number != null ? ProtoAdapter.STRING.encodedSizeWithTag(1, value.number) : 0)
              + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, Phone value) throws IOException {
      if (value.number != null) ProtoAdapter.STRING.encodeWithTag(writer, 1, value.number);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public Phone decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.number(ProtoAdapter.STRING.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public Phone redact(Phone value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  };

  private static final long serialVersionUID = 0L;

  public static final String DEFAULT_NUMBER = "";

  public final String number;

  public Phone(String number) {
    this(number, ByteString.EMPTY);
  }

  public Phone(String number, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.number = number;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.number = number;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof Phone)) return false;
    Phone o = (Phone) other;
    return Internal.equals(unknownFields(), o.unknownFields())
            && Internal.equals(number, o.number);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (number != null ? number.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (number != null) builder.append(", number=").append(number);
    return builder.replace(0, 2, "Phone{").append('}').toString();
  }

  public static final class Builder extends com.squareup.wire.Message.Builder<Phone, Builder> {
    public String number;

    public Builder() {
    }

    public Builder number(String number) {
      this.number = number;
      return this;
    }

    @Override
    public Phone build() {
      return new Phone(number, buildUnknownFields());
    }
  }
}
